import { bn } from './constants';

const BASE_URI_CATALOG = 'ipfs//'; // TODO, replace with actual IPFS

const SLOT_ELEMENT_GEM_ID = bn(1);
const SLOT_SKILL_GEM_ID = bn(2);
const SLOT_FACTION_GEM_ID = bn(3);
const SLOT_BACKGROUND_ID = bn(4);
const SLOT_HEAD_ID = bn(5);
const SLOT_CHEST_ID = bn(6);
const SLOT_BODY_ID = bn(7);
const SLOT_LEFT_HAND_ID = bn(8);
const SLOT_RIGHT_HAND_ID = bn(9);
const SLOT_BADGE_1_ID = bn(10);
const SLOT_BADGE_2_ID = bn(11);
const SLOT_BADGE_3_ID = bn(12);
const SLOT_BADGE_4_ID = bn(13);
const SLOT_BADGE_5_ID = bn(14);
const SLOT_EXTRA_1_ID = bn(15);
const SLOT_EXTRA_2_ID = bn(16);
const SLOT_EXTRA_3_ID = bn(17);
const SLOT_EXTRA_4_ID = bn(18);
const SLOT_EXTRA_5_ID = bn(19);

const FIXED_FRAME_COMMANDER_ID = bn(101);
const FIXED_FRAME_GENERAL_ID = bn(102);
const FIXED_FRAME_SOLDIER_ID = bn(103);

const Z_INDEX_BACKGROUND_SLOT = 0;
const Z_INDEX_FRAME_FIXED = 1;
const Z_INDEX_SNAKE = 5;
const Z_INDEX_ELEMENT_GEM_SLOT = 15;
const Z_INDEX_SKILL_GEM_SLOT = 14;
const Z_INDEX_FACTION_GEM_SLOT = 14;
const Z_INDEX_HEAD_SLOT = 6;
const Z_INDEX_CHEST_SLOT = 7;
const Z_INDEX_BODY_SLOT = 8;
const Z_INDEX_LEFT_HAND_SLOT = 9;
const Z_INDEX_RIGHT_HAND_SLOT = 10;
const Z_INDEX_BADGE_SLOT = 11;
const Z_INDEX_EXTRA_SLOT = 12;

const CATALOG_METADATA_URI = `${BASE_URI_CATALOG}/catalog.json`; 
const CATALOG_TYPE = 'img/png';
const SLOT_BACKGROUND_METADATA_URI = `${BASE_URI_CATALOG}/slots/background.json`; 
const SLOT_ELEMENT_GEM_METADATA_URI = `${BASE_URI_CATALOG}/slots/elementGem.json`; 
const SLOT_SKILL_GEM_METADATA_URI = `${BASE_URI_CATALOG}/slots/skillGem.json`;
const SLOT_FACTION_GEM_METADATA_URI = `${BASE_URI_CATALOG}/slots/factionGem.json`;
const SLOT_HEAD_METADATA_URI = `${BASE_URI_CATALOG}/slots/head.json`;
const SLOT_CHEST_METADATA_URI = `${BASE_URI_CATALOG}/slots/chest.json`;
const SLOT_BODY_METADATA_URI = `${BASE_URI_CATALOG}/slots/body.json`;
const SLOT_LEFT_HAND_METADATA_URI = `${BASE_URI_CATALOG}/slots/leftHand.json`;
const SLOT_RIGHT_HAND_METADATA_URI = `${BASE_URI_CATALOG}/slots/rightHand.json`;
const SLOT_BADGE_METADATA_URI = `${BASE_URI_CATALOG}/slots/badge.json`;
const SLOT_EXTRA_METADATA_URI = `${BASE_URI_CATALOG}/slots/extra.json`;

const FIXED_FRAME_GENERAL_METADATA_URI = `${BASE_URI_CATALOG}/fixed/generalFrame.json`; 
const FIXED_FRAME_COMMANDER_METADATA_URI = `${BASE_URI_CATALOG}/fixed/commanderFrame.json`; 
const FIXED_FRAME_SOLDIER_METADATA_URI = `${BASE_URI_CATALOG}/fixed/soldierFrame.json`; 

export {
  SLOT_ELEMENT_GEM_ID,
  SLOT_SKILL_GEM_ID,
  SLOT_FACTION_GEM_ID,
  SLOT_BACKGROUND_ID,
  SLOT_HEAD_ID,
  SLOT_CHEST_ID,
  SLOT_BODY_ID,
  SLOT_LEFT_HAND_ID,
  SLOT_RIGHT_HAND_ID,
  SLOT_BADGE_1_ID,
  SLOT_BADGE_2_ID,
  SLOT_BADGE_3_ID,
  SLOT_BADGE_4_ID,
  SLOT_BADGE_5_ID,
  SLOT_EXTRA_1_ID,
  SLOT_EXTRA_2_ID,
  SLOT_EXTRA_3_ID,
  SLOT_EXTRA_4_ID,
  SLOT_EXTRA_5_ID,
  FIXED_FRAME_COMMANDER_ID,
  FIXED_FRAME_GENERAL_ID,
  FIXED_FRAME_SOLDIER_ID,
  Z_INDEX_SNAKE,
  Z_INDEX_FRAME_FIXED,
  Z_INDEX_ELEMENT_GEM_SLOT,
  Z_INDEX_SKILL_GEM_SLOT,
  Z_INDEX_FACTION_GEM_SLOT,
  Z_INDEX_BACKGROUND_SLOT,
  Z_INDEX_HEAD_SLOT,
  Z_INDEX_CHEST_SLOT,
  Z_INDEX_BODY_SLOT,
  Z_INDEX_LEFT_HAND_SLOT,
  Z_INDEX_RIGHT_HAND_SLOT,
  Z_INDEX_BADGE_SLOT,
  Z_INDEX_EXTRA_SLOT,
  CATALOG_METADATA_URI,
  CATALOG_TYPE,
  SLOT_BACKGROUND_METADATA_URI,
  SLOT_ELEMENT_GEM_METADATA_URI,
  SLOT_SKILL_GEM_METADATA_URI,
  SLOT_FACTION_GEM_METADATA_URI,
  SLOT_HEAD_METADATA_URI,
  SLOT_CHEST_METADATA_URI,
  SLOT_BODY_METADATA_URI,
  SLOT_LEFT_HAND_METADATA_URI,
  SLOT_RIGHT_HAND_METADATA_URI,
  SLOT_BADGE_METADATA_URI,
  SLOT_EXTRA_METADATA_URI,
  FIXED_FRAME_COMMANDER_METADATA_URI,
  FIXED_FRAME_GENERAL_METADATA_URI,
  FIXED_FRAME_SOLDIER_METADATA_URI,
};
